baseURL = "https://www.johnegan.dev"
languageCode = "en-us"
title = "Website name"

relativeURLs = "true"
canonifyurls = "true"
enableRobotsTXT = "true"
# Site params
[params]
author = "John Egan"
home= "Home"
logo = "images/logo.png"
gmapAPI = "#"
shortname = "short name"
fullname = "Full name"
tagline ="website or business tagline"
description = "longer description of website used for meta description and social sharing purposes."
disallow_search_engines = false # set robots.txt to disallow everything
# Meta data
# Google Analitycs
googleAnalitycsID = "GA-ID"
googleTagManagerID = "GTM-ID"

copyrighthtml = "This work is licensed under a Creative Commons Attribution 4.0 International License."
